application: disc2017
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /disc\.ico
  static_files: disc.ico
  upload: disc\.ico

- url: /s
  static_dir: s

- url: .*
  script: disc2017.app


libraries:
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: "1.1.7"
- name: numpy
  version: "latest"
- name: jinja2
  version: "latest"
